SET NAMES utf8mb4;

INSERT INTO `Host` (`Host_Name`, `Marketing_Name`, `Title`, `Phone`, `Cell_Phone`, `Email`, `Host_ID`, `Image_Name`) VALUES
                                                                                                                         ('Nguyen, Alex',   'Alex Nguyen',    'Casino Host',                     '609-882-3444', NULL, 'anguyen@digitaldogdirect.com', NULL, 'alex_nguyen.jpg'),
                                                                                                                         ('Smith, Emily',   '',               '',                                '',            NULL, '', NULL, ''),
                                                                                                                         ('Le, Daniel',     'Daniel Le',      'Director Of International Marketing', '609-882-3444', NULL, 'dle@digitaldogdirect.com', NULL, 'daniel_le.jpg'),
                                                                                                                         ('Taylor, Chris',  '',               '',                                '',            NULL, '', NULL, ''),
                                                                                                                         ('Brown, Linda',   'Linda Brown',    'Executive Casino Host',           '609-882-3444', NULL, 'lbrown@digitaldogdirect.com', NULL, 'linda_brown.jpg'),
                                                                                                                         ('White, Sarah',   'Sarah White',    'Executive Casino Host',           '609-882-3444', NULL, 'swhite@digitaldogdirect.com', NULL, 'sarah_white.jpg'),
                                                                                                                         ('Harris, David',  'David Harris',   'Executive Casino Host',           '609-882-3444', NULL, 'dharris@digitaldogdirect.com', NULL, 'david_harris.jpg'),
                                                                                                                         ('Pham, Kevin',    'Kevin Pham',     'Executive Casino Host',           '609-882-3444', NULL, 'kpham@digitaldogdirect.com', NULL, 'kevin_pham.jpg'),
                                                                                                                         ('Walker, John',   'John Walker',    'Casino Host',                     '609-882-3444', NULL, 'jwalker@digitaldogdirect.com', NULL, 'john_walker.jpg'),
                                                                                                                         ('Lewis, Robert',  'Robert Lewis',   'Executive Casino Host',           '609-882-3444', NULL, 'rlewis@digitaldogdirect.com', NULL, 'robert_lewis.jpg');
